--- 
abstract: Normalize text based on the NACO rules
author: 
  - Brian Cassidy <bricas@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-Normalize-NACO
no_index: 
  directory: 
    - inc
    - t
requires: 
  Text::Unidecode: 0
  perl: 5.8.0
version: 0.12
