--- #YAML:1.0
name: Text-Normalize-NACO
version: 0.1
author:
  - Brian Cassidy <bricas@cpan.org>
abstract: Normalize text based on the NACO rules
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
